root : ukhsa/

sd2011_path : inputs/sd2011.csv
data_dict_path : inputs/data_dictionary.csv

out_folder : outputs/

recode_mapping:
  sex : 
    FEMALE : 1
    MALE : 2
    
output_columns:
  attributes:
  - id_hash
  both:
  - age
  - sex
 
hashing:
  old_id : id
  new_id : id_hash