root : ukhsa/

sd2011_path : sd2011.csv
data_dict_path : data_dictionary_sd2011.csv

out_folder : outputs/

recode_mapping:
  sex : 
    FEMALE : 1
    MALE : 2
    
output_columns_both:
 - age
 - sex